--
-- 09_customer.sql
-- 

ALTER TABLE `customer_eav_attribute`
    DROP COLUMN `is_used_for_customer_segment`;

ALTER TABLE `customer_entity`
    DROP INDEX `CUSTOMER_ENTITY_CREATED_AT`,
    DROP INDEX `CUSTOMER_ENTITY_DOB`,
    DROP INDEX `CUSTOMER_ENTITY_DEFAULT_BILLING`,
    DROP INDEX `CUSTOMER_ENTITY_DEFAULT_SHIPPING`,
    DROP INDEX `CUSTOMER_ENTITY_GENDER`,
    DROP INDEX `CUSTOMER_ENTITY_GROUP_ID`;
